# pmaports CI and "pmbootstrap kconfig check" use this file to ensure our
# kernels have certain kernel config options set. Which categories are checked
# depends on options="pmb:kconfigcheck-â€¦" in the linux APKBUILD. If no such
# option is set, see the default in ["category:default".">=0.0.0"."all"] below.

[aliases]
# Devices with options="pmb:kconfigcheck-community" in the device APKBUILD will
# check for the following categories. A CI check ensures that all devices in
# device/main and device/community dirs have this option. Devices in testing
# may also have "pmb:kconfigcheck-community", but it may be removed when
# modifying the required options and adjusting the devices in testing is too
# much effort. Device maintainers may fix it up afterwards and add it back.
community = [
	"category:default",
	"category:community_various",
	"category:containers",
	"category:debug",
	"category:filesystems",
	"category:input",
	"category:iwd",
	"category:netboot",
	"category:nftables",
	"category:usb_gadgets",
	"category:waydroid",
	"category:wireguard",
	"category:zram",
]

# Format for rule sections:
#   ["category:<NAME>"."<KERNEL_VERSION>"."<ARCHITECTURES>"]
# Implemented value types:
# - tristate (e.g. 'ANDROID_PARANOID_NETWORK = n'):
#   - y: built-in, preferred but module is OK
#   - m: module, preferred but built-in is OK
#   - n: disabled
# - list (e.g. 'ANDROID_BINDER_DEVICES = ["binder", "hwbinder"]'):
#   - each element of the array must be contained in the kernel config string,
#     in any order. The example above would accept the following in the config:
#       CONFIG_ANDROID_BINDER_DEVICES="hwbinder,vndbinder,binder"
# - string (e.g. 'LSM = "lockdown,yama,loadpin,safesetid,integrity"'):
#   - the value in the kernel config must be the same as the given string. Use
#     this e.g. if the order of the elements is important.

# default: all devices must satisfy these
["category:default".">=0.0.0"."all"]
ANDROID_PARANOID_NETWORK = "n"
BLK_DEV_INITRD = "y"
CGROUPS = "y"
CRYPTO_AES = "y"
CRYPTO_XTS = "y"
DEVTMPFS = "y"
DM_CRYPT = "y"
INPUT_EVDEV = "y"
EXT4_FS = "y"
KINETO_GAN = "n"
PFT = "n"
SEC_RESTRICT_ROOTING = "n"
SYSVIPC = "y"
TMPFS_POSIX_ACL = "y"
USE_VFB = "n"
VT = "y"
["category:default".">=2.6.0"."all"]
BINFMT_ELF = "y"
["category:default".">=3.10.0"."all"]
BINFMT_SCRIPT = "y"
["category:default".">=4.0.0"."all"]
UEVENT_HELPER = "y"
USER_NS = "y"
["category:default"."<4.7.0"."all"]
DEVPTS_MULTIPLE_INSTANCES = "y"
["category:default"."<4.14.0"."all"]
SAMSUNG_TUI = "n"
TZDEV = "n"
["category:default"."<5.2.0"."armhf armv7 x86"]
LBDAF = "y"
["category:default".">=5.2.0"."all"]
# Provide a proper dummy null console to improve compatibility
# on devices that like to coerce console=null
NULL_TTY = "y"
["category:default".">=5.19.0"."all"]
FW_LOADER_COMPRESS_ZSTD = "y"
["category:default".">=4.20.0"."all"]
# required for systemd-oomd
PSI = "y"
PSI_DEFAULT_DISABLED = "n"
UDMABUF = "y"

["category:netmount".">=2.6.0"."all"]
CACHEFILES = "y"
CRYPTO_AES = "y"
CRYPTO_CAMELLIA = "y"
CRYPTO_CBC = "y"
CRYPTO_CTS = "y"
CRYPTO_HMAC = "y"
CRYPTO_SHA256 = "y"
CRYPTO_SHA512 = "y"
FSCACHE = "y"
NFS_FS = "y"
NFS_FSCACHE = "y"
NFS_V3 = "y"
NFS_V4 = "y"
RPCSEC_GSS_KRB5 = "y"
["category:netmount".">=3.1.0"."all"]
CRYPTO_CMAC = "y"
["category:netmount".">=3.10.0"."all"]
CRYPTO_AES_TI = "y"
["category:netmount".">=3.10.0"."aarch64"]
CRYPTO_AES_ARM64_CE_BLK = "y"
["category:netmount".">=4.14.0"."all"]
RPCSEC_GSS_KRB5_ENCTYPES_AES_SHA1 = "y"
RPCSEC_GSS_KRB5_ENCTYPES_AES_SHA2 = "y"
RPCSEC_GSS_KRB5_ENCTYPES_CAMELLIA = "y"

# waydroid: android compatibility layer
["category:waydroid".">=0.0.0"."all"]
ANDROID_BINDERFS = "n"
ANDROID_BINDER_DEVICES = ["binder", "hwbinder", "vndbinder"]
ANDROID_BINDER_IPC = "y"
ANDROID_BINDER_IPC_SELFTEST = "n"
BLK_DEV_LOOP = "y"
BPF_SYSCALL = "y"
BRIDGE = "y"
BRIDGE_VLAN_FILTERING = "y"
CGROUP_BPF = "y"
FUSE_FS = "y"
IP_NF_MANGLE = "y"
NETFILTER_XTABLES = "y"
NETFILTER_XT_MATCH_COMMENT = "y"
SQUASHFS = "y"
SQUASHFS_XATTR = "y"
SQUASHFS_XZ = "y"
TMPFS_XATTR = "y"
TUN = "y"
VETH = "y"
VLAN_8021Q = "y"  # prerequisite for bridge
["category:waydroid".">=3.5"."all"]
CROSS_MEMORY_ATTACH = "y"
["category:waydroid".">=4.20.0"."all"]
PSI = "y"  # required by userspace OOM killer
PSI_DEFAULT_DISABLED = "n"
["category:waydroid"."<5.18"."all"]
ASHMEM = "y"

# iwd: modern inet wireless daemon
# Obtained from 'grep ADD_MISSING src/main.c' in iwd.git
["category:iwd".">=0.0.0"."all"]
ASYMMETRIC_KEY_TYPE = "y"
ASYMMETRIC_PUBLIC_KEY_SUBTYPE = "y"
CRYPTO_AES = "y"
CRYPTO_CBC = "y"
CRYPTO_CMAC = "y"
CRYPTO_DES = "y"
CRYPTO_ECB = "y"
CRYPTO_HMAC = "y"
CRYPTO_MD4 = "y"  # Needed for EAP MSCHAPV2 authentication
CRYPTO_MD5 = "y"
CRYPTO_SHA1 = "y"
CRYPTO_SHA256 = "y"
CRYPTO_SHA512 = "y"
CRYPTO_USER_API_HASH = "y"
CRYPTO_USER_API_SKCIPHER = "y"
KEYS = "y"
KEY_DH_OPERATIONS = "y"
PKCS7_MESSAGE_PARSER = "y"
PKCS8_PRIVATE_KEY_PARSER = "y"
X509_CERTIFICATE_PARSER = "y"
RFKILL = "y"

# nftables: firewall, not related to nft scams
["category:nftables".">=3.13.0"."all"]
NETFILTER = "y"
NF_CONNTRACK = "y"
NF_TABLES = "y"
NF_TABLES_INET = "y"
NFT_CT = "y"
NFT_LOG = "y"
NFT_LIMIT = "y"
NFT_MASQ = "y"
NFT_NAT = "y"
NFT_REJECT = "y"
NF_TABLES_IPV4 = "y"
NF_REJECT_IPV4 = "y"
IP_NF_IPTABLES = "y"
IP_NF_FILTER = "y"
IP_NF_TARGET_REJECT = "y"
IP_NF_NAT = "y"
NF_TABLES_IPV6 = "y"
NF_REJECT_IPV6 = "y"
IP6_NF_IPTABLES = "y"
IP6_NF_FILTER = "y"
IP6_NF_TARGET_REJECT = "y"
IP6_NF_NAT = "y"
["category:nftables".">=3.13.0 <0.17"."all"]
NFT_COUNTER = "y"

# containers: lxc, docker, etc.
["category:containers".">=0.0.0"."all"]
NAMESPACES = "y"
NET_NS = "y"
PID_NS = "y"
IPC_NS = "y"
UTS_NS = "y"
CGROUPS = "y"
CGROUP_CPUACCT = "y"
CGROUP_DEVICE = "y"
CGROUP_FREEZER = "y"
CGROUP_SCHED = "y"
CPUSETS = "y"
KEYS = "y"
VETH = "y"
BRIDGE = "y"  # (also needed for waydroid)
BRIDGE_NETFILTER = "y"
IP_NF_FILTER = "y"
IP_NF_TARGET_MASQUERADE = "y"
NETFILTER_XT_MATCH_ADDRTYPE = "y"
NETFILTER_XT_MATCH_CONNTRACK = "y"
NETFILTER_XT_MATCH_IPVS = "y"
NETFILTER_XT_MARK = "y"
NETFILTER_XT_TARGET_CHECKSUM = "y"  # Needed for lxc
IP_NF_NAT = "y"
NF_NAT = "y"
POSIX_MQUEUE = "y"
BLK_DEV_DM = "y"  # Storage Drivers
DUMMY = "y"  # Network Drivers
# USER_NS = "y"  # This is already in pmOS kconfig check
BLK_CGROUP = "y"  # Optional section
BLK_DEV_THROTTLING = "y"  # Optional section
CGROUP_PERF = "y"  # Optional section
NET_SCHED = "y" # Required by NET_CLS_CGROUP
NET_CLS_CGROUP = "y"  # Optional section
FAIR_GROUP_SCHED = "y"  # Optional section
IP_NF_TARGET_REDIRECT = "y"  # Optional section
IP_VS = "y"  # Optional section
IP_VS_NFCT = "y"  # Optional section
IP_VS_PROTO_TCP = "y"  # Optional section
IP_VS_PROTO_UDP = "y"  # Optional section
IP_VS_RR = "y"  # Optional section
# EXT4_FS = "y"  # This is already in pmOS kconfig check
EXT4_FS_POSIX_ACL = "y"  # Optional section
EXT4_FS_SECURITY = "y"  # Optional section
["category:containers".">=3.2"."all"]
CFS_BANDWIDTH = "y"  # Optional section
["category:containers".">=3.3"."all"]
CHECKPOINT_RESTORE = "y"  # Needed for lxc
["category:containers".">=3.6"."all"]
MEMCG = "y"
DM_THIN_PROVISIONING = "y"  # Storage Drivers
SWAP = "y"
["category:containers".">=3.6"."x86 x64_64"]
HUGETLB_PAGE = "y"
CGROUP_HUGETLB = "y"  # Optional section
["category:containers".">=3.6 <6.1_rc1"."all"]
MEMCG_SWAP = "y"
["category:containers".">=3.7 <5.0"."all"]
NF_NAT_IPV4 = "y"  # Needed for lxc
NF_NAT_IPV6 = "y"  # Needed for lxc
["category:containers".">=3.7"."all"]
VXLAN = "y"  # Network Drivers
IP6_NF_TARGET_MASQUERADE = "y"  # Needed for lxc
["category:containers".">=3.9"."all"]
BRIDGE_VLAN_FILTERING = "y"  # Network Drivers (also for waydroid)
MACVLAN = "y"  # Network Drivers
["category:containers".">=3.13"."all"]
NFT_COMPAT = "y"
["category:containers".">=3.14"."all"]
CGROUP_NET_PRIO = "y"  # Optional section
["category:containers".">=3.18"."all"]
OVERLAY_FS = "y"  # Storage Drivers
["category:containers".">=3.19"."all"]
IPVLAN = "y"  # Network Drivers
SECCOMP = "y"  # Optional section
["category:containers".">=4.4"."all"]
CGROUP_PIDS = "y"  # Optional section

# zram: RAM disk with on-the-fly compression
["category:zram".">=0.0.0"."all"]
ZRAM = "y"
ZSMALLOC = "y"
SWAP = "y"

["category:zram"."<6.12"."all"]
CRYPTO_ZSTD = "y"

["category:zram".">=6.12"."all"]
ZRAM_BACKEND_ZSTD = "y"

# netboot: https://postmarketos.org/netboot
["category:netboot".">=0.0.0"."all"]
BLK_DEV_NBD = "y"

# wireguard: VPN software, also includes options for wg-quick
["category:wireguard".">=5.6_rc1"."all"]
WIREGUARD = "y"
IP_ADVANCED_ROUTER = "y"
IP_MULTIPLE_TABLES = "y"
IPV6_MULTIPLE_TABLES = "y"
NF_TABLES = "y"
NF_TABLES_IPV4 = "y"
NF_TABLES_IPV6 = "y"
NFT_CT = "y"
NFT_FIB = "y"
NFT_FIB_IPV4 = "y"
NFT_FIB_IPV6 = "y"
NF_CONNTRACK_MARK = "y"

# filesystems
["category:filesystems".">=0.0.0"."all"]
BTRFS_FS = "y"
EXFAT_FS = "y"
EXT4_FS = "y"
F2FS_FS = "y"
UDF_FS = "y"
XFS_FS = "y"

# usb_gadgets
["category:usb_gadgets".">=0.0.0"."all"]
# disable legacy gadgets
USB_ETH = "n"
USB_FUNCTIONFS = "n"
USB_MASS_STORAGE = "n"
USB_G_SERIAL = "n"
# enable configfs gadgets
USB_CONFIGFS_ACM = "y"  # Serial gadget for debug-shell
USB_CONFIGFS_MASS_STORAGE = "y"  # Mass storage gadget for debug-shell
USB_CONFIGFS_NCM = "y"  # USB networking via NCM
USB_CONFIGFS_RNDIS = "y"  # USB networking via RNDIS (legacy)

# community_various: Various options that were not categorized properly due to
# inflexibility of previous kconfigcheck related code. We should move these to
# proper categories above and/or invent new categories with meaningful names.
# >> Do not add more here!! <<
["category:community_various".">=0.0.0"."all"]
BINFMT_MISC = "y"  # register binary formats
NETWORK_FILESYSTEMS = "y"  # Required by CIFS
CIFS = "y"  # mount SMB shares
LEDS_TRIGGER_PATTERN = "y"  # feedbackd
LEDS_TRIGGER_TIMER = "y"  # hfd-service
NETFILTER_XT_MATCH_MARK = "y"  # e.g. HashiCorp Nomad
NETFILTER_XT_MATCH_MULTIPORT = "y"  # e.g. HashiCorp Nomad
NETFILTER_XT_MATCH_STATISTIC = "y"  # kube-proxy
NETFILTER_XT_MATCH_TCPMSS = "y"  # change MTU e.g. for Wireguard
NETFILTER_XT_TARGET_TCPMSS = "y"  # change MTU e.g. for Wireguard
# TODO = Depends on SUSPEND which is not enabled for some devices
# PM_WAKELOCKS = "y"  # Sxmo
UCLAMP_TASK = "y"  # Scheduler hints
UCLAMP_TASK_GROUP = "y"  # Scheduler hints
RT_GROUP_SCHED = "n"  # https://gitlab.postmarketos.org/postmarketOS/pmaports/-/issues/2652
DM_INTEGRITY = "y"  # Device-mapper integrity target

# uefi: proper modern booting
["category:uefi".">=0.0.0"."all"]
EFI_STUB = "y"
EFI = "y"
DMI = "y"
PSTORE = "y"
EFI_ESRT = "y"
EFI_VARS_PSTORE = "y"
EFI_RUNTIME_WRAPPERS = "y"
VFAT_FS = "y"
NLS_ASCII = "y"
["category:uefi".">=0.0.0"."x86_64"]
EFI_MIXED = "y"
["category:uefi".">=0.0.0"."aarch64 armv7"]
EFI_GENERIC_STUB = "y"
EFI_PARAMS_FROM_FDT = "y"
["category:uefi".">=6.1.0"."aarch64"]
# Required EFI booting compressed kernels on this arch
EFI_ZBOOT = "y"
# Devices that used to run windows may still want to access
# the windows partition (e.g. to retrieve firmware on WoA)
["category:uefi".">=5.15"."aarch64 x86_64"]
NTFS3_FS = "y"

["category:input".">=0.0.0"."all"]
BT_HIDP = "y"  # Bluetooth HID
HIDRAW = "y"  # /dev/hidraw* support
INPUT_UINPUT = "y"  # buffyboard
INPUT_JOYSTICK = "y" # Required by CONFIG_JOYSTICK_XPAD_FF
JOYSTICK_XPAD = "y"  # Xbox controller
JOYSTICK_XPAD_FF = "y"  # Xbox controller force-feedback
JOYSTICK_XPAD_LEDS = "y"  # Xbox controller LEDs
UHID = "y"  # User-space HID, e.g. Bluetooth
USB_ANNOUNCE_NEW_DEVICES = "y"  # dmesg messages when connecting device
USB_HIDDEV = "y"  # /dev/usb/hiddevX support
USB_PRINTER = "y"  # printers
# All the special HID drivers that Fedora kernel enables
HID_A4TECH = "y"
HID_ACCUTOUCH = "y"
HID_ACRUX_FF = "y"
HID_ACRUX = "y"
HID_ALPS = "y"
HID_APPLEIR = "y"
HID_APPLE = "y"
HID_AUREAL = "y"
HID_BATTERY_STRENGTH = "y"
HID_BELKIN = "y"
HID_BETOP_FF = "y"
HID_BIGBEN_FF = "y"
HID_CHERRY = "y"
HID_CHICONY = "y"
HID_CMEDIA = "y"
HID_CORSAIR = "y"
HID_COUGAR = "y"
HID_CP2112 = "y"
HID_CREATIVE_SB0540 = "y"
HID_CYPRESS = "y"
HID_DRAGONRISE = "y"
HID_ELAN = "y"
HID_ELECOM = "y"
HID_ELO = "y"
HID_EMS_FF = "y"
HID_EZKEY = "y"
HID_FT260 = "y"
HID_GEMBIRD = "y"
HID_GENERIC = "y"
HID_GFRM = "y"
HID_GLORIOUS = "y"
HID_GREENASIA = "y"
HID_GT683R = "y"
HID_GYRATION = "y"
HID_HOLTEK = "y"
HID_ICADE = "y"
HID_ITE = "y"
HID_JABRA = "y"
HID_KENSINGTON = "y"
HID_KEYTOUCH = "y"
HID_KYE = "y"
HID_LCPOWER = "y"
HID_LED = "y"
HID_LETSKETCH = "y"
HID_LOGITECH_DJ = "y"
HID_LOGITECH_HIDPP = "y"
HID_LOGITECH = "y"
HID_MACALLY = "y"
HID_MAGICMOUSE = "y"
HID_MALTRON = "y"
HID_MAYFLASH = "y"
HID_MCP2221 = "y"
HID_MEGAWORLD_FF = "y"
HID_MICROSOFT = "y"
HID_MONTEREY = "y"
HID_MULTITOUCH = "y"
HID_NINTENDO = "y"
HID_NTI = "y"
HID_NTRIG = "y"
HID_ORTEK = "y"
HID_PANTHERLORD = "y"
HID_PENMOUNT = "y"
HID_PETALYNX = "y"
HID_PICOLCD_BACKLIGHT = "y"
LCD_CLASS_DEVICE = "y" # Required by HID_PICOLCD_LCD
HID_PICOLCD_LCD = "y"
HID_PICOLCD_LEDS = "y"
HID_PICOLCD = "y"
HID_PID = "y"
HID_PLANTRONICS = "y"
HID_PLAYSTATION = "y"
HID_PRIMAX = "y"
HID_PRODIKEYS = "y"
HID_PXRC = "y"
HID_RAZER = "y"
HID_RETRODE = "y"
HID_RMI = "y"
HID_ROCCAT = "y"
HID_SAITEK = "y"
HID_SAMSUNG = "y"
HID_SEMITEK = "y"
HID_SENSOR_ACCEL_3D = "y"
HID_SENSOR_ALS = "y"
HID_SENSOR_CUSTOM_INTEL_HINGE = "y"
HID_SENSOR_DEVICE_ROTATION = "y"
HID_SENSOR_GYRO_3D = "y"
HID_SENSOR_HUB = "y"
HID_SENSOR_HUMIDITY = "y"
HID_SENSOR_IIO_COMMON = "y"
HID_SENSOR_IIO_TRIGGER = "y"
HID_SENSOR_INCLINOMETER_3D = "y"
HID_SENSOR_MAGNETOMETER_3D = "y"
HID_SENSOR_TEMP = "y"
HID_SIGMAMICRO = "y"
HID_SMARTJOYPLUS = "y"
HID_SONY = "y"
HID_SPEEDLINK = "y"
HID_STEAM = "y"
HID_STEELSERIES = "y"
HID_SUNPLUS = "y"
HID_THINGM = "y"
HID_THRUSTMASTER = "y"
HID_TIVO = "y"
HID_TOPRE = "y"
HID_TOPSEED = "y"
HID_TWINHAN = "y"
HID_U2FZERO = "y"
HID_UCLOGIC = "y"
HID_UDRAW_PS3 = "y"
HID_VIEWSONIC = "y"
HID_VIVALDI = "y"
HID_WACOM = "y"
HID_WALTOP = "y"
HID_WIIMOTE = "y"
HID_XIAOMI = "y"
HID_XINMO = "y"
HID_ZEROPLUS = "y"
HID_ZYDACRON = "y"
["category:input".">=0.0.0"."x86 x86_64"]
HID_LENOVO = "y"
["category:input".">=6.3"."all"]
HID_EVISION = "y"
HID_SUPPORT = "y"
["category:input".">=6.5"."all"]
HID_NVIDIA_SHIELD = "y"
["category:input".">=6.6"."all"]
HID_GOOGLE_STADIA_FF = "y"
["category:input".">=6.10"."all"]
HID_WINWING = "y"
["category:input".">=6.12"."all"]
HID_GOODIX_SPI = "y"
["category:input".">=0.0.0"."riscv64 x86 x86_64"]
HID_BPF = "y"
["category:input".">=6.4.0"."aarch64"]
HID_BPF = "y"
["category:input".">=4.15.0"."all"]
BPF_JIT = "y" # Required by HID_BPF

["category:usb".">=0.0.0"."all"]
DRM_UDL = "y"  # DisplayLink - connecting displays via USB
SND_USB_AUDIO = "y"  # USB audio devices
USB_SERIAL_CP210X = "y"  # USB serial console
USB_STORAGE = "y"  # USB mass storage devices
USB_RTL8152 = "y"  # USB Ethernet

["category:virt".">=0.0.0"."all"]
HW_RANDOM_VIRTIO = "y"
KVM = "y"
VIRTUALIZATION = "y"

["category:debug".">=0.0.0"."all"]
FTRACE = "y" # Required by DEBUG_FTRACE
FUNCTION_TRACER = "y" # Required by DEBUG_FTRACE
DYNAMIC_DEBUG = "y"  # Enable debug dynamically
DYNAMIC_FTRACE = "y"  # Enable function tracing dynamically

# Device specific settings to prevent regressions
["category:librem5".">=0.0.0"."aarch64"]
RS9116_FLASH_MODE = "n"  # pma!2059
["category:pinephonepro".">=0.0.0"."aarch64"]
LEDS_GROUP_MULTICOLOR = "y"  # pma!5991
